// Stack solves from the community guide "Colosseum Stack Solves" (Help Me RNG, with ro0b0 and
// ItzSynpah). The guide's own words, kept as written apart from light tidying, so a stack it covers
// can show its advice alongside ours. Every stack in it is laid out at the north-west pillar, so a
// match is on the shape of the stack rather than its absolute position.
//
// Source: https://docs.google.com/document/d/e/2PACX-1vR3IqdspMrEAbH60-Z9cOKpM8-H5U49q6ZgqU8wTFSXIj_kAx69qyKakuyMOm2oLRvdV2cGNK2B0kmZ/pub
import type { Mob } from "./types";

export const GUIDE_URL = "https://docs.google.com/document/d/e/2PACX-1vR3IqdspMrEAbH60-Z9cOKpM8-H5U49q6ZgqU8wTFSXIj_kAx69qyKakuyMOm2oLRvdV2cGNK2B0kmZ/pub";
export const GUIDE_TITLE = "Colosseum Stack Solves";
export const GUIDE_AUTHORS = "Help Me RNG, ro0b0 and ItzSynpah";

export type GuideSolve = {
  /** [x, y, type, manticore orb pattern] as the guide lays the stack out. */
  mobs: [number, number, number, string | null][];
  label: string;
  steps: string[];
  /** The guide's verdict that this stack cannot be solved - you have to tank something. */
  unwinnable?: boolean;
};

export const GUIDE_SOLVES: GuideSolve[] = [
  { mobs: [[14, 10, 1, null], [11, 10, 2, null]], label: "Range + shaman", steps: ["Start center tile", "Move 2 tiles south praying mage, then pray range"] },
  { mobs: [[11, 10, 2, null], [14, 10, 4, "m"]], label: "Range + manticore(mage)", steps: ["Start center tile", "Move 2 tiles south praying mage, then pray range and then melee. The ranger is same-ticked with the manticores range attack"] },
  { mobs: [[14, 10, 4, "r"], [11, 10, 6, null]], label: "Mage + manticore(range)", steps: ["Start center tile", "Move 2 tiles south praying range, then pray mage and then melee. The ranger is same-ticked with the manticores range attack"] },
  { mobs: [[11, 9, 1, null], [12, 9, 2, null]], label: "shaman + range", steps: ["Start from the center of the pillar", "Run 2 tiles north praying range, then swap to mage"] },
  { mobs: [[11, 9, 4, "r"], [14, 9, 6, null]], label: "manticore(range) + mage", steps: ["Start center of pillar", "Run 2 tiles south praying mage; then pray range, mage, and melee. They are offticked"] },
  { mobs: [[11, 9, 2, null], [14, 9, 2, null], [17, 9, 6, null]], label: "range + range + mage", steps: ["Start center of pillar and move 1 tile back", "Run 2 tiles south praying mage; then pray range. The rangers are same ticked but are off-tick from the mager"] },
  { mobs: [[17, 9, 1, null], [14, 9, 2, null], [11, 9, 4, "r"]], label: "manticore(range) + range + shaman", steps: ["Start on the southern most tile behind the pillar", "Take 1 step west", "Walk out 1 tile praying range→mage→melee. The shaman cannot see you", "After the melee orb, walk 1 tile east praying mage to offtick them; or simply kill the minotaur from a distance", "Alternatively, you can triple destack using the guide above"] },
  { mobs: [[11, 10, 2, null], [17, 10, 2, null], [14, 10, 6, null]], label: "range + mage + range", steps: ["This is a “Z-stack”. An example is linked in #inferno", "Stand in the center of pillar; move 2 tiles west", "Tick 1: Run 2 tiles south praying range", "Tick 2: return to the pillar middle tile (hugging pillar)", "Tick 3: run 2 tiles south praying mage", "Tick 4: pray range", "Tick 5: null", "Cycle repeats; 5→R’; 6→null; 7→ mage; 8→ range; 9→null; repeat"] },
  { mobs: [[17, 9, 2, null], [11, 9, 6, null], [14, 9, 6, null]], label: "mage + mage +", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south praying range; then pray mage"] },
  { mobs: [[14, 9, 2, null], [17, 9, 2, null], [11, 9, 6, null]], label: "mage + range + range", steps: ["Start at the center of the pillar", "Run 2 tiles south praying range; then pray mage"] },
  { mobs: [[11, 11, 2, null], [14, 11, 2, null], [17, 11, 4, "m"]], label: "range + range + manticore(mage)", steps: ["Start middle of pillar", "Take 1 step back", "Run 2 tiles south praying mage then range. The range attacks are same ticked"] },
  { mobs: [[17, 10, 4, "r"], [11, 11, 6, null], [14, 11, 6, null]], label: "mage + mage + manticore(range)", steps: ["Start middle of pillar", "Take 1 step back", "Run 2 tiles south praying range then mage. The mage attacks are same ticked"] },
  { mobs: [[14, 9, 2, null], [11, 9, 6, null], [17, 9, 6, null]], label: "mage + range + mage", steps: ["This is a “Z-stack. An example is linked in #inferno", "Stand in the center of the pillar. Move 2 tiles back", "Tick 1: Run 2 tiles south praying mage", "Tick 2: return to the pillar middle tile (hugging pillar)", "Tick 3: run 2 tiles south praying range", "Tick 4: pray mage", "Tick 5: null", "Cycle repeats; 5→M’; 6→null; 7→ R; 8→ M; 9→null; repeat", "OR force a triple destack (see the start of this section). You will tank a range hit"] },
  { mobs: [[14, 9, 4, "r"], [11, 10, 6, null], [17, 9, 6, null]], label: "Mage + manticore(range) + range", steps: ["This is a “Z-stack. An example is linked in #inferno. Live-view at", "Stand in the center of the pillar. Move 2 tiles back", "Tick 1: Run 2 tiles south praying mage", "Tick 2: return to the pillar middle tile (hugging pillar)", "Tick 3: run 2 tiles south praying range", "Tick 4: pray mage", "Tick 5: null", "Cycle repeats; 5→M’; 6→null; 7→ R; 8→ M; 9→null; repeat", "OR force a triple destack (see the start of this section). You will tank a range hit"] },
  { mobs: [[14, 9, 2, null], [17, 9, 4, "r"], [11, 9, 6, null]], label: "Mage + range + manticore(range)", steps: ["Start at the center of the pillar", "Run 2 tiles south praying range; then pray mage then melee. The ranger and manticore range attack are same-ticked"] },
  { mobs: [[11, 11, 2, null], [17, 10, 4, "r"], [14, 10, 6, null]], label: "Range + mage + manticore(range)", steps: ["live replay of solve at", "This is a “Z-stack” with an extra step", "Start at the center of the pillar; move 2 tiles back", "Tick 1: Run 2 tiles south praying range", "Tick 2: run back behind the pillar (hugging it from the center) praying mage", "Tick 3: pray melee", "Tick 4: step 2 tiles south praying mage", "Tick 5:pray range", "They are now off-ticked; M-R-R-M-mel-M-R"] },
  { mobs: [[14, 9, 2, null], [17, 9, 4, "m"], [11, 9, 6, null]], label: "Range + mage + manticore(mage)", steps: ["Live replay of solve at", "This is a “Z-stack” with an extra step", "Start at the center of the pillar; move 2 tiles back", "Tick 1: Run 2 tiles south praying mage", "Tick 2: run back behind the pillar (hugging it from the center) praying range", "Tick 3: pray meleel", "Tick 4:step 2 tiles south praying mage", "Tick 5:pray range", "They are now off-ticked; R-M-M-R-mel-R-M"] },
  { mobs: [[17, 10, 2, null], [11, 10, 4, "r"], [14, 10, 6, null]], label: "manticore(range) + mage + range", steps: ["Solve tick-by-tick is", "Option 1: Run south praying mage. PLAN IT OUT SO THEY DON’T RE-STACK THIS SAME WAY", "Do not do this"] },
  { mobs: [[17, 9, 2, null], [11, 9, 4, "r"], [14, 9, 6, null]], label: "Instead you want to temporarily step out west again to force the mager and manticore to stack in a 1 + 1", steps: ["Option 2: constantly repeat step 1 of option 3 until the ranger does his javelin. Then do https://clips.twitch.tv/SincereCrazyToothDerp-WXkCYvHbxffT6OVt to drag the ranger down", "Option 3: The messy one: – there are alterations of the", "This is a “Z-stack ”with an extra step", "Stand in the center of the pillar. Move 2 tiles back", "Tick 1: Run 2 tiles south praying range", "Tick 2: return to the pillar middle tile (hugging pillar)", "Tick 3: run 2 tiles south praying mage", "Tick 4: pray range", "Tick 5: pray mage WHILE YOU GO BACK BEHIND PILLAR (southernmost tile of the pillar; touching it)", "Tick 6: pray melee", "Tick 7: run back 2 tiles south praying range", "Tick 8: pray mage", "Cycle repeats; 9→Null’; 10→null; 11→null", "12→ R; 13→Mage; 14 → R; 15 → mage; 16 → mel; 17 →R; 18 →mage; repeat", "Option 4:", "force a triple destack (see the start of this section). You will tank a mage hit"] },
  { mobs: [[14, 10, 2, null], [11, 11, 4, "m"], [17, 10, 6, null]], label: "manticore(mage) + range + mage", steps: ["Solve tick-by-tick is", "Option 1: Run south praying mage. PLAN IT OUT SO THEY DON’T RE-STACK THIS SAME WAY", "See “manticore(range) + mage + range:” as an example to prevent a bad re-stack", "Option 2: The messy one: This is a “Z-stack ”with an extra step", "Stand in the center of the pillar. Move 2 tiles back", "Tick 1: Run 2 tiles south praying mage", "Tick 2: return to the pillar middle tile (hugging pillar)", "Tick 3: run 2 tiles south praying range", "Tick 4: pray mage", "Tick 5: pray range WHILE YOU GO BACK BEHIND PILLAR (southern-most tile of the pillar; touching it)", "Tick 6: pray melee", "Tick 7: run back 2 tiles south praying mage", "Tick 8: pray range", "Cycle repeats; 9→Null’; 10→null; 11→null", "12→ Mage; 13→; 14 → Mage; 15 → R; 16 → mel; 17 →mage; 18 →R; repeat", "Option 3:", "force a triple destack (see the start of this section). You will tank a range hit"] },
  { mobs: [[14, 9, 2, null], [17, 9, 4, "m"], [11, 9, 4, "m"]], label: "manticore(mage) + range + manticore(mage)", steps: ["Solve at . The solve here depends on whether the front or back manticore attacks you. Each has their own separate solve and you won’t know until one attacks; there is a risk you tank a hit. This is assuming you don’t know which one will attack", "Start middle of pillar", "Take 1 step back", "Run 2 tiles south praying mage then immediately run 2 tiles north east (touching the middle of the pillar) praying range then melee then range then melee", "The second you see the melee orb launch, run back out 2 tiles south praying range-mage-range-melee"] },
  { mobs: [[11, 10, 2, null], [17, 10, 2, null], [14, 10, 4, "m"]], label: "Range + manticore(mage) + range", steps: ["This is a “Z-stack”. An example is linked in #inferno", "Stand in the center of pillar; move 2 tiles west", "Tick 1: Run 2 tiles south praying range", "Tick 2: return to the pillar middle tile (hugging pillar)", "Tick 3: run 2 tiles south praying mage", "Tick 4: pray range", "Tick 5: pray melee", "The back ranger and the manticore are now sameticked in their range attack", "If there is no manticore behind the NE pillar (see above) you can do a “triple destack drag” bring the ranger down. You will tank a range hit doing so"] },
  { mobs: [[11, 9, 2, null], [14, 9, 4, "r"], [17, 9, 6, null]], label: "Range + manticore(range) + mage", steps: ["Start in the middle of pillar", "Take 1 step west", "Run 2 tiles south praying mage then range then mage then melee. The ranger and manticore are same-ticked"] },
  { mobs: [[17, 9, 2, null], [11, 9, 4, "m"], [14, 9, 4, "m"]], label: "manticore(mage) + manticore(mage) + range", steps: ["Start from middle of pillar", "Take 1 step west", "Run 2 tiles south praying range → mage → range → melee"] },
  { mobs: [[11, 9, 1, null], [12, 9, 2, null], [15, 9, 2, null]], label: "Shaman + range + range", steps: ["Start in the middle of pillar", "Run 2 tiles north praying range then mage", "You can then either kill the serpent or go behind the pillar to drag it to and turn it to a 1+1 range stack"] },
  { mobs: [[11, 10, 1, null], [14, 9, 2, null], [11, 9, 4, "m"]], label: "manticore(mage)/shaman + ranger", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south praying mage then range. This lures the shaman out; you can either kill them while they’re offticked or bring the shaman behind the pillar and then solve"] },
  { mobs: [[11, 8, 1, null], [14, 9, 2, null], [11, 11, 4, "m"]], label: "manticore(mage)/shaman + ranger", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south praying mage then pray range then pray melee. They now have their range attack same-ticked"] },
  { mobs: [[11, 11, 2, null], [11, 8, 2, null], [14, 10, 4, "m"]], label: "range/range + manticore(mage)", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south praying range then pray mage then pray range then pray melee"] },
  { mobs: [[14, 9, 1, null], [11, 8, 2, null], [11, 11, 4, "r"]], label: "manticore(range)/ranger + shaman", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south praying range then mage", "Take 1 step back", "Run 2 tiles north, praying range then mage"] },
  { mobs: [[14, 9, 2, null], [11, 11, 4, "m"], [11, 8, 4, "m"]], label: "manticore(mage)/manticore(mage) + ranger", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south; praying mage then range then melee. Their range attacks are sameticked"] },
  { mobs: [[11, 11, 4, "r"], [11, 8, 4, "r"], [14, 9, 6, null]], label: "manticore(range)/manticore(range) + mage", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south; praying range then mage then melee. Their mage attacks are sameticked"] },
  { mobs: [[14, 9, 1, null], [11, 9, 2, null], [11, 12, 4, "r"]], label: "manticore(range)/ranger + shaman", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south; praying range then mage then melee. Their mage attacks are sameticked"] },
  { mobs: [[11, 8, 2, null], [11, 11, 4, "r"], [14, 10, 6, null]], label: "Manticore(range)/ranger + mager", steps: ["Start at the center of the pillar", "Take 1 step back", "Run 2 tiles south; praying range then mage"] },
  { mobs: [[14, 9, 2, null], [11, 11, 4, "m"], [11, 8, 6, null]], label: "Manticore(mage)/mager + ranger", steps: ["Start at the center of the pillar", "Take 2 steps back", "Run 2 tiles south; praying mage then range then melee. Their range autos are sameticked"] },
  { mobs: [[14, 9, 2, null], [11, 8, 4, "m"], [11, 11, 6, null]], label: "Manticore(mage)/mager + ranger", steps: ["Start at the center of the pillar", "Take 1 steps back", "Run south 2 tiles praying mage then range"] },
  { mobs: [[11, 11, 2, null], [11, 8, 2, null], [14, 9, 4, "m"]], label: "Manticore(mage)/mager + ranger", steps: ["Start at the center of the pillar", "Take 1 steps back", "Run south 2 tiles praying range then mage then range then melee"] },
  { mobs: [[11, 8, 1, null], [12, 8, 2, null], [11, 11, 4, "r"], [14, 11, 6, null]], label: "manticore(range)/shaman + ranger/mager", steps: ["You have to tank a shaman or ranger here. Step out 1 tile north praying range and then go back behind the pillar. The shaman will follow you; transforming this into a 2+1 stack"] },
  { mobs: [[14, 8, 1, null], [11, 8, 2, null], [11, 11, 4, "r"], [14, 11, 6, null]], label: "manticore(range)/shaman + ranger/mager", steps: ["Start at the center of the pillar", "Move 4 tiles back", "Step 2 tiles north praying range. You then have a few options:", "you can kill the ranger without the shaman ever seeing you if 8+ range weaponry", "You move closer and manually off-tick the shaman and then kill it (then hide behind pillar to reset to a 2+1)"] },
  { mobs: [[11, 8, 1, null], [14, 11, 2, null], [14, 8, 2, null], [11, 11, 4, "m"]], label: "manticore(mage)/shaman + ranger/ranger", steps: ["Go all the way back and step 1 tile out north praying range or mage for 1 tick; this will drag the shaman in and turn it to a 1+2 or 2+1 stack"] },
  { mobs: [[11, 10, 1, null], [14, 11, 2, null], [14, 8, 2, null], [11, 9, 4, "m"]], label: "manticore(mage)/shaman + ranger/ranger", steps: ["Go all the way back and step 1 tile out south praying range or mage for 1 tick; this will drag the shaman in and turn it to a 1+2 or 2+1 stack"] },
  { mobs: [[14, 7, 1, null], [11, 11, 2, null], [11, 8, 4, "r"], [14, 10, 6, null]], label: "manticore(range)/ranger + shaman/mager", steps: ["Go all the way to the wall", "Step north praying against the manticore; the shaman cannot see you. Either kill the manticore or kill the by timing the offtick so the mage attacks line up. This is a difficult maneuver"] },
  { mobs: [[14, 11, 1, null], [11, 11, 2, null], [11, 8, 4, "r"], [14, 10, 6, null]], label: "manticore(range)/ranger + shaman/mager", steps: ["Go to the center of the pillar", "Take 1 step back", "Run 2 tiles south praying range then mage. Kill the ranger first"] },
  { mobs: [[14, 8, 1, null], [11, 8, 2, null], [14, 11, 2, null], [11, 11, 4, "m"]], label: "manticore(mage)/ranger + shaman/ranger", steps: ["Go all the way to the wall", "Step north praying range; the shaman cannot see you. Either kill the ranger or kill the shaman", "If your attack distance was nerfed, perform a manual off-tick by moving up after seeing the ranger attack you"] },
  { mobs: [[14, 10, 1, null], [11, 11, 2, null], [14, 9, 2, null], [11, 8, 4, "m"]], label: "manticore(mage)/ranger + shaman/ranger", steps: ["Step back to the wall while standing on the southernmost tile of safety behind the pillar", "Run south 2 tiles praying range and the shaman will lure itself out; pray mage after both rangers attack you and then go behind the pillar again", "OR you can simply just kill the front ranger from the back without the shaman seeing you"] },
  { mobs: [[14, 11, 2, null], [11, 11, 4, "r"], [11, 8, 4, "m"], [14, 8, 6, null]], label: "manticore(range)/manticore(mage) + ranger/mager", steps: ["You have to tank something here. I’d suggest just doing your best to protect against mage projectiles while wearing tank armor and running south"], unwinnable: true },
  { mobs: [[14, 11, 2, null], [14, 8, 2, null], [11, 11, 4, "m"], [11, 8, 6, null]], label: "manticore(mage)/mager + ranger/ranger", steps: ["You have to tank something here. I’d suggest just doing your best to protect against mage projectiles while wearing tank armor and running south"], unwinnable: true },
  { mobs: [[11, 8, 2, null], [14, 11, 2, null], [11, 11, 4, "m"], [14, 8, 4, "m"]], label: "manticore(mage)/ranger + manticore(mage)/ranger", steps: ["You have to tank something here. I’d suggest just doing your best to protect against mage projectiles while wearing tank armor and running south"], unwinnable: true },
  { mobs: [[11, 8, 2, null], [11, 11, 4, "r"], [14, 8, 4, "m"], [14, 11, 6, null]], label: "manticore(range)/ranger + manticore(mage)/mager", steps: ["You have to tank something here. I’d suggest just doing your best to protect against mage projectiles while wearing tank armor and running south"], unwinnable: true },
  { mobs: [[11, 8, 2, null], [14, 11, 4, "r"], [14, 8, 4, "m"], [11, 11, 6, null]], label: "mager/ranger + manticore(range)/manticore(mage)", steps: ["You have to tank something here. I’d suggest just doing your best to protect against mage projectiles while wearing tank armor and running south"], unwinnable: true },
  { mobs: [[14, 8, 1, null], [11, 8, 2, null], [14, 11, 4, "r"], [11, 11, 6, null]], label: "mager/ranger + manticore(range)/shaman", steps: ["Go all the way to the back of the wall", "Step 1 tile north praying range; only the ranger can see you. Either kill the ranger from far away or time the manual off-tick (don’t get so close that the manticore sees you)"] },
  { mobs: [[14, 10, 1, null], [11, 11, 2, null], [14, 9, 4, "r"], [11, 8, 6, null]], label: "ranger/mage + shaman/manticore(range)", steps: ["Start from the center of the pillar", "Step back 1 tile", "Run 2 tiles south praying range then mage"] },
  { mobs: [[11, 11, 2, null], [11, 8, 2, null], [14, 8, 4, "m"], [14, 11, 6, null]], label: "ranger/ranger + manticore/mager", steps: ["You have to tank something here. I’d suggest just doing your best to protect against mage projectiles while wearing tank armor and running south"], unwinnable: true },
  { mobs: [[11, 11, 2, null], [11, 8, 2, null], [14, 8, 4, "m"], [14, 11, 4, "m"]], label: "Ranger/ranger + manticore(mage)/manticore(mage)", steps: ["You can’t even stepunder to force an offtick. You have to run south. I recommend running the way I’ve planned out here. Take careful note of where I’m starting to run from and how i path. This is so the manticores do not both fire on you at the same time", "Done correctly, you will tank a singular range or melee hit (your choice)"], unwinnable: true },
  { mobs: [[14, 8, 2, null], [14, 11, 2, null], [11, 11, 4, "m"], [11, 8, 4, "m"]], label: "manticore(mage)/manticore(mage) + ranger/ranger", steps: ["You can’t even stepunder to force an offtick. You have to run south. I recommend running the way I’ve planned out here. Take careful note of where I’m starting to run from and how i path. This is so the manticores do not both fire on you at the same time", "Done correctly, you will tank a singular range hit"], unwinnable: true },
  { mobs: [[11, 8, 2, null], [14, 11, 4, "r"], [11, 11, 6, null], [14, 8, 6, null]], label: "mage/range + manticore(range)/mage", steps: ["– you have to tank something here while running south", "Start at the middle of the pillar", "Run south praying mage; you will tank a range hit and melee hit (unless you flick the melee)"], unwinnable: true },
  { mobs: [[11, 8, 2, null], [11, 11, 4, "r"], [14, 9, 6, null], [17, 9, 6, null]], label: "manticore(range)/range + mage + mage", steps: ["You have to tank a range hit here", "Start in the center; run out south 2 tiles praying mage (all 3 monsters will hit you)", "Run back behind the pillar praying mage then melee", "The second you see the melee manticore hit fly out, go north praying range. As long as you did it quick enough, the ranger and the two magers will have 1-2 ticks of difference between their attacks. You get one tick to mess this up/do it slowly and still be fine", "MORE BELOW KEEP READING"] },
  { mobs: [[11, 8, 2, null], [11, 11, 4, "m"], [17, 9, 4, "m"], [14, 9, 6, null]], label: "manticore(mage)/range + mage + manticore(mage)", steps: ["You want to sametick the manticore(s) and the shockwave here", "Touch the pillar", "Move to the southernmost tile (see red square)", "Run 2 tiles south praying mage-range-melee. The mage attacks are sameticked"] },
  { mobs: [[11, 8, 2, null], [17, 9, 4, "r"], [11, 11, 6, null], [14, 9, 6, null]], label: "mage/range + mage + manticore(range)", steps: ["Go all the way west", "Be on the southernmost tile of the pillar", "Take 1 step out praying mage; after the magers attack, run up praying against the manticore. You only have two ticks to do this, else the magers/manticore will be sameticked"] },
  { mobs: [[11, 11, 2, null], [17, 9, 2, null], [14, 9, 4, "m"], [11, 8, 6, null]], label: "range/mage + manticore(mage) + range", steps: ["Start middle of pillar", "Take 1 step west", "Run 2 tiles south praying range, then mage, then range, then melee. The rangers are same-ticked"] },
  { mobs: [[11, 8, 2, null], [17, 9, 2, null], [14, 9, 4, "m"], [11, 11, 6, null]], label: "mage/range + manticore(mage) + range", steps: ["Start on the southernmost tile of pillar", "Go all the way west", "Run 1 tiles south praying mage and then pray mage", "The manticore + shocker have their mage attack same ticked", "The manticore + ranger have their range attack same ticked", "Run east so you can kill the stack"] },
  { mobs: [[11, 11, 2, null], [14, 9, 2, null], [11, 8, 4, "m"], [17, 9, 4, "m"]], label: "range/manticore(mage) + range + manticore(mage)", steps: ["Start southernmost tile of the pillar", "Run all the way west", "Run out 1 tile praying range to same-tick the rangers"] },
  { mobs: [[11, 11, 2, null], [17, 9, 2, null], [11, 8, 4, "m"], [14, 9, 4, "m"]], label: "range/manticore(mage) + manticore(mage)+ range", steps: ["Start middle of pillar", "Take 1 step west", "Run south 2 tiles praying range (same ticks the rangers) then pray against the manticore. Kill the manticore ideally"] },
  { mobs: [[11, 11, 2, null], [11, 8, 2, null], [17, 9, 4, "m"], [14, 9, 6, null]], label: "range/range+ mage + manticore(mage)", steps: ["This might be a run south angle. It has a really weird solve that you only get 1 shot of doing correct", "Go to the southern most tile of the pillar; go all the way west", "Complete a “Triple destack” and run back to the MIDDLE of the pillar", "Wait until the manticore is almost off it’s attack cool down and then step 1 tile south praying range then pray against the manticore"] },
  { mobs: [[11, 11, 2, null], [11, 8, 2, null], [17, 9, 4, "r"], [14, 9, 6, null]], label: "range/range+ mage + manticore(range)", steps: ["Start middle of pillar", "Take 1 step west", "Run south 2 tiles praying range (same ticks the ranger and manticore) then pray against the mager (same ticks the ranger and manticore). Kill the mager ideally"] },
  { mobs: [[11, 11, 2, null], [17, 9, 2, null], [11, 8, 4, "r"], [14, 7, 5, null], [14, 10, 6, null]], label: "range/manticore(range) + mage/minotaur + range", steps: ["Start the northern most tile of the pillar", "Step 3 tiles west (see", "Run 1 tile north praying range; then 2 tiles north praying mage then melee. Then go back behind the pillar to turn it to a 2+1+1 and lure the minotaur"] },
  { mobs: [[17, 9, 2, null], [20, 9, 2, null], [11, 11, 4, "m"], [11, 8, 6, null], [14, 9, 6, null]], label: "mage/manticore(mage) + mage + range + range", steps: ["This is actually pretty solvable!!", "Stand on the southern most tile of the pilar", "Go all the way west", "Step out 1 tile praying mage (step 3)", "immediately run two tiles east praying range then pray melee", "After the melee attack fires out, run 2 more tiles east praying range. You now have a awkward offtick", "OR run south praying mage beginning with step 3 mentioned above"] },
  { mobs: [[14, 11, 2, null], [11, 8, 4, "r"], [14, 8, 4, "r"], [11, 11, 6, null], [17, 9, 6, null]], label: "mage/manticore(range) + range/manticore(range) + mage", steps: ["Follow →"] },
  { mobs: [[14, 11, 2, null], [11, 8, 4, "r"], [14, 8, 4, "r"], [11, 11, 6, null], [17, 10, 6, null]], label: "mage/manticore(range) + range/manticore(range) + mage", steps: ["Start on the southern most tile behind the pillar", "Run 1 tile south praying mage", "Run 4 tiles north praying range-mage-melee", "Pray mage then range", "Run south → note that you WILL have two mobs to deal with here that WILL be sameticked unless you do", "Afterwards, you will be left with", "Do a double triple destack", "To add list:", "All four manticore combos of this"] },
];

/** What a stack looks like regardless of where on the map it sits: types, orb patterns, and the
 *  offsets between the mobs. Two stacks with the same signature play the same way. */
function signature(mobs: Array<[number, number, number, string | null]>) {
  if (mobs.length === 0) return "";
  const minX = Math.min(...mobs.map((m) => m[0]));
  const minY = Math.min(...mobs.map((m) => m[1]));
  return mobs
    .map(([x, y, type, extra]) => `${x - minX},${y - minY},${type},${(extra ?? "").slice(0, 1)}`)
    .sort()
    .join("|");
}

const BY_SIGNATURE = new Map<string, GuideSolve>();
for (const solve of GUIDE_SOLVES) {
  const key = signature(solve.mobs);
  if (!BY_SIGNATURE.has(key)) BY_SIGNATURE.set(key, solve);
}

/** The guide's entry for this stack, if it has one. Read off where the mobs started and the orb
 *  pattern they were placed with, so the match holds while a solve is replaying. */
export function matchGuideSolve(mobs: Mob[]): GuideSolve | null {
  const live = mobs
    .filter((m) => m[2] > 0 && m[2] < 8)
    .map(
      (m) =>
        [m[3] ?? m[0], m[4] ?? m[1], m[2], ((m[7] ?? m[6]) as string | null) ?? null] as
          [number, number, number, string | null],
    );
  if (live.length === 0) return null;
  return BY_SIGNATURE.get(signature(live)) ?? null;
}
